__authors__ = "Ad de Roo, Emiliano Gelati, Peter Burek, Johan van der Knijff, Niko Wanders"
__version__ = "2.8.6"
__date__ = "13 May 2019"
__copyright__ = "Copyright 2019, European Commission - Joint Research Centre"
__maintainer__ = "Emiliano Gelati, Domenico Nappo, Valerio Lorini, Ad de Roo"
__status__ = "Operation"
